"""
Evidence Storage.

Stores evidence generated by
validation and cleaning rules.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(slots=True)
class Evidence:
    """
    Single evidence object.
    """

    rule: str

    description: str

    created_at: datetime = field(
        default_factory=datetime.utcnow
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


class EvidenceStore:
    """
    In-memory evidence repository.
    """

    def __init__(
        self,
    ) -> None:

        self._items: list[Evidence] = []

    def add(
        self,
        evidence: Evidence,
    ) -> None:

        self._items.append(
            evidence
        )

    def create(
        self,
        rule: str,
        description: str,
        **metadata: Any,
    ) -> None:

        self.add(

            Evidence(

                rule=rule,

                description=description,

                metadata=metadata,

            )

        )

    @property
    def items(
        self,
    ) -> tuple[Evidence, ...]:

        return tuple(
            self._items
        )

    def clear(
        self,
    ) -> None:

        self._items.clear()

    def __len__(
        self,
    ) -> int:

        return len(
            self._items
        )

    def __iter__(
        self,
    ):

        return iter(
            self._items
        )